### ISSUE TITLE
"Sea All" button on homepage a bit misleading

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/ai-crowd-3#197]
_From @spMohanty on May 31, 2017 15:45_

The "See All" button on the home page for the challenges is a bit misleading.
Especially because the section header is "Challenges"

When I first landed on the page, I thought there were only a total of 3 challenges. And it took me some time to notice the "See All" button too.

Moving the "See All" button to something like a "Load More" button on the Challenges page(https://www.crowdai.org/challenges) might make more sense I think ?

Also changing the title to "Featured Challenges" might be more correct ?

cc. @jsnrynlds 

_Copied from original issue: crowdAI/crowdai#140_

**Comment by marcelsalathe** [comment]
I agree with the title change to "Featured Challenges"

I also agree that "See all" functionality should be duplicated on the home page using the same mechanism as the "Load More" button on the Challenges page.

I would also prefer to hide the "Load More" Button until we have something like a min of 20 challenges.
