### ISSUE TITLE
US economic sanctions in the terms page :-?

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/ai-crowd-3#201]
_From @spMohanty on May 31, 2017 16:05_

We have a clause in our terms of service page which says :

_09. US Economic Sanctions
You expressly represent and warrant that your use of our Services and or associated services and products is not contrary to applicable U.S. Sanctions. Such use is prohibited, and crowdAI reserve the right to terminate accounts or access of those in the event of a breach of this condition._

Link : https://www.crowdAI.org/pages/terms

Is this intentional :-? ?

_Copied from original issue: crowdAI/crowdai#144_

**Comment by marcelsalathe** [comment]
I agree, let's remove this
