### ISSUE TITLE
Leaderboard videos not rendering in Learning to Walk challenge

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/ai-crowd-3#239]
_From @spMohanty on July 03, 2017 08:48_

Link : https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards

Update: Maybe the videos just all load after a long delay. But this still needs to be investigated.

_Copied from original issue: crowdAI/crowdai#239_

**Comment by marcelsalathe** [comment]
They do indeed take forever. As the leaderboards are growing rapidly now, we should probably start showing just the top X (say 20), and load more on demand (i.e. using the show more button we have on the homepage).

**Comment by spMohanty** [comment]
@seanfcarroll : Depending on the performance, I would like to have at least the videos from say the top-5 submissions running on page load. 

It is easy to miss that these are videos, and also, given a broad overview of (at least) a few good different policies learn by just loading the leaderboard, was something both participants and externals have loved about the Learning to Walk and the Learning to Run challenge.

@marcelsalathe @seanfcarroll : What do you think ?
